# Generated by Django 2.2.3 on 2019-07-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('news_source', models.CharField(max_length=50)),
                ('news_content', models.TextField(default='')),
                ('publish_time', models.DateTimeField(null=True)),
                ('news_status', models.CharField(default='0', max_length=2)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
